spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: song-service

server:
  port : 8082

eureka:
  client.serviceUrl.defaultZone: http://localhost:8761/eureka/